import { carsForSaleType, sparePartsSaleType } from "@src/types/types";

export const carsForSale: carsForSaleType = [
  {
    id: 1,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 2,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 3,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 4,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 5,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 6,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 7,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 8,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 9,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 10,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 11,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 12,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 13,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 14,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 15,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 16,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
  {
    id: 17,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
    year: "2008",
    make: "Toyota",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Black",
    interior: "Red",
  },
  {
    id: 18,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
    year: "2021",
    make: "Lexus",
    model: "C300 4Matic",
    millage: "16490 Miles",
    trim: "SE 4dr Sedan",
    condition: "Excellent Condition",
    color: "Grey",
    interior: "Black",
  },
];

export const homeHeader = [
  {
    name: "Home",
    list: [
      {
        name: "Category Listing",
        screen: "Category",
      },
    ],
  },
  {
    name: "Services",
    list: [
      {
        name: "Car Sales (Tokunbo and Naija Used)",
        screen: "Category",
      },
      {
        name: "Car Hire (Personal, Commercial, Logistics)",
        screen: "CarsForHire",
      },
      {
        name: "Spare Parts",
        screen: "SpareParts",
      },
      {
        name: "Consultation Services",
        screen: "ConsultationService",
      },
      {
        name: "Dealers Deal",
        screen: "DealersDeal",
      },
    ],
  },
  {
    name: "Profile",
    list: [
      {
        name: "Wishlist",
        screen: "",
      },
      {
        name: "Recently Viewed",
        screen: "",
      },
    ],
  },
];

export const otherService = [
  {
    list: "Car Hire",
    screen: "",
  },
  {
    list: "Spare Parts",
    screen: "",
  },
  {
    list: "Consultation Services",
    screen: "",
  },
  {
    list: "Dealers Deal",
    screen: "",
  },
];

export const sparePartsForSale: sparePartsSaleType = [
  {
    id: 1,
    name: "Toyota Corolla Rims",
    price: 20000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 2,
    name: "Brake Pads",
    price: 9000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 3,
    name: "Toyota Corolla Rims",
    price: 20000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 4,
    name: "Brake Pads",
    price: 9000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 5,
    name: "Toyota Corolla Rims",
    price: 20000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 6,
    name: "Brake Pads",
    price: 9000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 7,
    name: "Toyota Corolla Rims",
    price: 20000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 8,
    name: "Brake Pads",
    price: 9000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 9,
    name: "Toyota Corolla Rims",
    price: 20000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 10,
    name: "Brake Pads",
    price: 9000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 11,
    name: "Toyota Corolla Rims",
    price: 20000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 12,
    name: "Brake Pads",
    price: 9000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 13,
    name: "Toyota Corolla Rims",
    price: 20000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 14,
    name: "Brake Pads",
    price: 9000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/spare-parts.png"),
    location: "Molete, Ibadan",
  },
];
