import { carsForSaleType } from "@src/types/types";

export const carsForSale: carsForSaleType = [
  {
    id: 1,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 2,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 3,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 4,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 5,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 6,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 7,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 8,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 9,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 10,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 11,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 12,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 13,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 14,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 15,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 16,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
  {
    id: 17,
    name: "2008 Toyota Camry Sport",
    price: 8000000,
    usedType: "Naija",
    carType: "Automatic",
    image: require("@src/assets/png/car1.png"),
    location: "Challenge, Ibadan",
  },
  {
    id: 18,
    name: "2021 Lexus Rx350 FSPORT",
    price: 10000000,
    usedType: "Foreign",
    carType: "Automatic",
    image: require("@src/assets/png/car2.png"),
    location: "Molete, Ibadan",
  },
];
